version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci(dependabot):"
    target-branch: "main"
    groups:
      actions:
        patterns:
          - "actions/*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    groups:
      dependencies:
        patterns:
          - "**"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      javascript-dependencies:
        patterns:
          - "*"
