version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci(dependabot):"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
