exclude: '^docs/'
repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
    -   id: mypy
        name: mypy
        additional_dependencies: [types-PyYAML, types-requests, pydantic]
-   repo: https://github.com/pycqa/pydocstyle
    rev: '6.3.0'
    hooks:
    -   id: pydocstyle
        exclude: tests/
        args: [--select, "D101,D102,D103,D105,D106"]
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
      args: [--skip, "B101,B303,B110,B311"]
-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
-   repo: https://github.com/myint/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--ignore-init-module-imports"]
