exclude: '^docs/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'
    hooks:
    -   id: mypy
        name: mypy
        additional_dependencies: [types-PyYAML, types-requests]
-   repo: https://github.com/pycqa/pydocstyle
    rev: '6.1.1'
    hooks:
    -   id: pydocstyle
        exclude: tests/
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
      args: [--skip, "B101,B303,B110"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    -   id: flake8
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: parsable-R
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.18.3
  hooks:
    - id: check-jsonschema
      name: "Check FHIR json"
      language: python
      files: ^FHIR/.*\.fhir.json
      #types: [json]
      args: ["--schemafile", "FHIR/fhir.schema.json"]
