from tests._testdata import concepts

criteria_defs = {
    "COVID19": {"type": "condition", "static": True},
    "VENOUS_THROMBOSIS": {"type": "condition", "static": True},
    "HIT2": {"type": "condition", "static": True},
    "HEPARIN_ALLERGY": {"type": "observation", "static": True},
    "HEPARINOID_ALLERGY": {"type": "observation", "static": True},
    "THROMBOCYTOPENIA": {"type": "condition", "static": True},
    # 'pulmonary_embolism': {'type': 'condition', 'static': True},
    # 'ards': {'type': 'condition', 'static': True},
    "WEIGHT": {
        "type": "observation",
        "static": True,
        "threshold": 70,
        "unit_concept_id": concepts.UNIT_KG,
    },
    "DALTEPARIN": {
        "type": "drug",
        "dosage_threshold": 5000,
        "doses_per_day": [0, 5],
        "p_dose_specific_day": 0.2,
        "static": False,
    },
    "ENOXAPARIN": {
        "type": "drug",
        "dosage_threshold": 40,
        "doses_per_day": [0, 5],
        "p_dose_specific_day": 0.2,
        "static": False,
    },
    "NADROPARIN_LOW_WEIGHT": {
        "type": "drug",
        "dosage_threshold": 3800,
        "doses_per_day": [0, 5],
        "p_dose_specific_day": 0.2,
        "static": False,
    },
    "NADROPARIN_HIGH_WEIGHT": {
        "type": "drug",
        "dosage_threshold": 5700,
        "doses_per_day": [0, 5],
        "p_dose_specific_day": 0.2,
        "static": False,
    },
    "CERTOPARIN": {
        "type": "drug",
        "dosage_threshold": 3000,
        "doses_per_day": [0, 5],
        "p_dose_specific_day": 0.2,
        "static": False,
    },
    "FONDAPARINUX": {
        "type": "drug",
        "dosage": 2.5,
        "doses_per_day": [0, 5],
        "p_dose_specific_day": 0.2,
        "static": False,
    },
    "HEPARIN": {"type": "drug", "dosage": 1, "doses_per_day": [0, 5], "static": False},
    "ARGATROBAN": {
        "type": "drug",
        "dosage": 1,
        "doses_per_day": [0, 5],
        "static": False,
    },
    "ICU": {
        "type": "visit",
        "range": [0, 30],
        "n_occurrences": [0, 2],
        "static": False,
    },
    "PRONING": {
        "type": "procdure",
        "range": [1, 20],
        "n_occurrences": [0, 20],
        "static": False,
    },
    "VENTILATED": {
        "type": "procedure",
        "range": [1, 20],
        "n_occurrences": [0, 20],
        "static": False,
    },
    "D_DIMER": {
        "type": "measurement",
        "threshold": 2,
        "range": [0, 4],
        "static": False,
        "unit_concept_id": concepts.UNIT_MG_PER_L,
    },
    "APTT": {
        "type": "measurement",
        "threshold": 50,
        "static": False,
        "unit_concept_id": concepts.UNIT_SECOND,
    },
    "TIDAL_VOLUME": {
        "type": "measurement",
        "threshold": 6,
        "range": [2, 10],
        "static": False,
        "occurrences_per_day": [6, 30],
        "static": False,
        "unit_concept_id": concepts.UNIT_ML,
    },
    "PMAX": {
        "type": "measurement",
        "threshold": 30,
        "range": [10, 100],
        "occurrences_per_day": [6, 30],
        "static": False,
        "unit_concept_id": concepts.UNIT_CM_H2O,
    },
    "FiO2": {
        "type": "measurement",
        "range": [0, 1.0],
        "occurrences_per_day": [6, 30],
        "static": False,
        "unit_concept_id": concepts.UNIT_PERCENT,
    },
    "PEEP": {
        "type": "measurement",
        "range": [4, 20],
        "occurrences_per_day": [6, 30],
        "static": False,
        "unit_concept_id": concepts.UNIT_CM_H2O,
    },
    "OXYGENATION_INDEX": {
        "type": "measurement",
        "range": [100, 200],
        "occurrences_per_day": [6, 30],
        "static": False,
        "unit_concept_id": concepts.UNIT_MM_HG,
    },
}
